# Generated by Django 5.0.2 on 2026-07-28 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='estoque/solicitacoes/')),
                ('status', models.CharField(choices=[('SOL', 'Solicitado'), ('COM', 'Comprado'), ('REC', 'Recebido'), ('RET', 'Retirado')], default='SOL', max_length=3)),
                ('referencia', models.CharField(blank=True, default='', max_length=50)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=100)),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=30)),
                ('preco_unitario', models.FloatField(blank=True, null=True)),
                ('preco_total', models.FloatField(blank=True, null=True)),
                ('data_compra', models.DateTimeField(blank=True, null=True)),
                ('local_estoque', models.CharField(blank=True, default='', max_length=50)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('almoxarifado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_recebidos', to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_comprados', to=settings.AUTH_USER_MODEL)),
                ('retirado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_retirados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=150)),
                ('referencia', models.CharField(blank=True, default='', max_length=50)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=100)),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=30)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.FloatField()),
                ('preco_total', models.FloatField()),
                ('local_estoque', models.CharField(max_length=50)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='estoque.itemsolicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_estoque', to='ativos.equipamentos')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemsolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.solicitacao'),
        ),
    ]
