# Generated by Django 5.0.2 on 2026-08-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        ('controleCEQ', '0009_alter_entrada_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroTaxaDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.FloatField(help_text='Ex: 5 para 5%')),
                ('vigente_desde', models.DateField()),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='CaminhaoAbastecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=30)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('descricao_locacao', models.TextField(default='Locação de CAMINHÃO DE ABASTECIMENTO, combustível diesel, sem operador, sendo o fornecimento de combustível por conta da LOCATÁRIA;')),
                ('ativo', models.BooleanField(default=True)),
                ('tanque', models.OneToOneField(limit_choices_to={'tipo': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='caminhao_abastecedor', to='controleCEQ.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='ValorMensalCaminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('vigente_desde', models.DateField()),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_mensais', to='medicao.caminhaoabastecedor')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='ContratoMedicaoCaminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('mes_referencia_inicial', models.DateField(help_text='Primeiro mês (dia 1) controlado pelo Kaito. Meses anteriores ficam só no saldo inicial abaixo.')),
                ('numero_anterior', models.IntegerField(default=0, help_text='Último número de medição usado antes do Kaito (planilha).')),
                ('quantidade_anterior_locacao', models.FloatField(default=0)),
                ('valor_anterior_locacao', models.FloatField(default=0)),
                ('quantidade_anterior_diesel', models.FloatField(default=0)),
                ('valor_anterior_diesel', models.FloatField(default=0)),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='medicao.caminhaoabastecedor')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_medicao_caminhao', to='ativos.obras')),
            ],
            options={
                'unique_together': {('obra', 'caminhao')},
            },
        ),
    ]
