# Generated by Django 5.0.2 on 2026-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0002_fechamentomedicaocaminhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomedicaocaminhao',
            name='mes_referencia_inicial',
            field=models.DateField(help_text='Primeiro mês (dia 1) controlado pelo Kaito. Meses anteriores não aparecem na grade de medição.'),
        ),
        migrations.AlterField(
            model_name='contratomedicaocaminhao',
            name='numero_anterior',
            field=models.IntegerField(default=0, help_text='Número da última medição fechada (do boletim físico mais recente). A próxima medição gerada será este número + 1 — atualize aqui sempre que fechar uma medição.'),
        ),
        migrations.AlterField(
            model_name='contratomedicaocaminhao',
            name='quantidade_anterior_diesel',
            field=models.FloatField(default=0, help_text='Litros de diesel acumulados até a última medição fechada.'),
        ),
        migrations.AlterField(
            model_name='contratomedicaocaminhao',
            name='quantidade_anterior_locacao',
            field=models.FloatField(default=0, help_text='Quantidade (em meses) acumulada até a última medição fechada.'),
        ),
        migrations.AlterField(
            model_name='contratomedicaocaminhao',
            name='valor_anterior_diesel',
            field=models.FloatField(default=0, help_text='Valor (R$) da taxa de diesel acumulado até a última medição fechada.'),
        ),
        migrations.AlterField(
            model_name='contratomedicaocaminhao',
            name='valor_anterior_locacao',
            field=models.FloatField(default=0, help_text='Valor (R$) de locação acumulado até a última medição fechada.'),
        ),
    ]
