# Generated by Django 5.0.2 on 2026-08-24 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0006_alter_obras_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nota_fiscal', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=50)),
                ('data_nf', models.DateField()),
                ('data_entrega', models.DateField()),
                ('quantidade', models.FloatField()),
                ('preco_unitario', models.FloatField()),
                ('preco_total', models.FloatField()),
                ('descricao', models.TextField(blank=True, default='')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_diesel', to='ativos.obras')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=30)),
                ('descricao', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(choices=[('R', 'ROCHA'), ('T', 'TERCEIRIZADO')], default='R', max_length=5)),
                ('unidade_medicao', models.CharField(choices=[('KM', 'Quilometragem'), ('H', 'Horímetro')], default='H', max_length=5)),
                ('contador_atual', models.FloatField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_diesel', to='ativos.obras')),
            ],
            options={
                'unique_together': {('obra', 'prefixo')},
            },
        ),
        migrations.CreateModel(
            name='SaidaDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('litros', models.FloatField()),
                ('contador_inicio', models.FloatField()),
                ('contador_fim', models.FloatField()),
                ('data', models.DateField()),
                ('operador', models.CharField(max_length=50)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='controle_diesel_obra.equipamentoobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_diesel', to='ativos.obras')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='TanqueObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.FloatField(default=0)),
                ('estoque', models.FloatField(default=0)),
                ('descricao', models.TextField(blank=True, default='')),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tanque_diesel', to='ativos.obras')),
            ],
        ),
    ]
