# Generated by Django 4.1.5 on 2024-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=20)),
                ('capacidade', models.IntegerField()),
                ('estoque', models.FloatField()),
                ('tipo', models.CharField(choices=[('F', 'fixo'), ('M', 'movel')], default='fixo', max_length=5)),
                ('descricao', models.TextField(default='')),
                ('contador', models.FloatField(default=0)),
            ],
        ),
    ]
