# Generated by Django 4.1.5 on 2024-02-22 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0002_obras_endereço'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controleCEQ', '0005_remove_abastecimento_colaborador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=20)),
                ('capacidade', models.IntegerField()),
                ('estoque', models.FloatField()),
                ('tipo', models.CharField(choices=[('F', 'fixo'), ('M', 'movel')], default='fixo', max_length=5)),
                ('descricao', models.TextField(default='')),
                ('contador', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_inicio', models.FloatField()),
                ('contador_fim', models.FloatField()),
                ('litros', models.FloatField()),
                ('contador_comboio', models.FloatField(default=0)),
                ('data', models.DateField(default='2022-01-01')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fixo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixo_tanque', to='controleCEQ.tanque')),
                ('movel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movel_tanque', to='controleCEQ.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=50)),
                ('data_nf', models.DateField(default=datetime.date(2022, 1, 1))),
                ('data_entrega', models.DateField(default=datetime.date(2022, 1, 1))),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_unitario', models.FloatField()),
                ('preco_total', models.FloatField()),
                ('descricao', models.TextField(default='')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.obras')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controleCEQ.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('contador_inicio', models.FloatField()),
                ('contador_fim', models.FloatField()),
                ('horimetro', models.FloatField()),
                ('data', models.DateField()),
                ('lubrificacao', models.BooleanField(default=False)),
                ('operador', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('observacao', models.CharField(default='', max_length=100, null='')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.obras')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controleCEQ.tanque')),
            ],
        ),
    ]
