# Generated by Django 4.1.5 on 2024-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleCEQ', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
