# Generated by Django 4.1.5 on 2024-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleCEQ', '0007_abastecimento_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
