# Generated by Django 5.0.2 on 2024-07-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleCEQ', '0008_entrada_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
    ]
