# Generated by Django 4.1.5 on 2024-01-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=None, upload_to='fotos'),
        ),
    ]
