# Generated by Django 4.1.5 on 2024-01-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_alter_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
    ]
