# Generated by Django 5.0.2 on 2026-07-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0012_usuario_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil_estoque',
            field=models.CharField(blank=True, choices=[('solicitante', 'Solicitante'), ('comprador', 'Comprador'), ('almoxarifado', 'Almoxarifado')], default='', max_length=20),
        ),
    ]
