# Generated by Django 5.0.2 on 2024-03-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0003_obras_distancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tempo_aguardo_peca', models.FloatField()),
                ('tempo_aguardo_servico', models.FloatField()),
                ('tempo_em_servico', models.FloatField()),
                ('status', models.CharField(choices=[('AP', 'Aguardando Peças'), ('AS', 'Aguardando Serviço'), ('ES', 'Em Serviço')], default='Aguardando Peças', max_length=5)),
                ('numero', models.IntegerField()),
                ('horimetro', models.FloatField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
            ],
        ),
    ]
