# Generated by Django 4.1.5 on 2024-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_oficina',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_em_servico',
            field=models.FloatField(null=True),
        ),
    ]
