# Generated by Django 4.1.5 on 2024-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_alter_ordem_oficina_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_oficina',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
