# Generated by Django 5.0.2 on 2024-04-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_alter_ordem_oficina_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servico_Terceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='status',
            field=models.CharField(choices=[('AP', 'Aguardando Peças'), ('AS', 'Aguardando Serviço'), ('ES', 'Em Serviço')], default='Aguardando Serviço', max_length=5),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_em_servico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Servico_Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('status', models.CharField(choices=[('AP', 'Aguardando Peças'), ('AS', 'Aguardando Serviço'), ('ES', 'Em Serviço')], default='Aguardando Peças', max_length=5)),
                ('descricao', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(null=True)),
                ('executante_funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('grupo_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.grupo_servico')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.ordem_oficina')),
                ('executante_terceiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_terceirizado')),
            ],
        ),
    ]
