# Generated by Django 5.0.2 on 2024-04-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_funcionario_grupo_servico_servico_terceirizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_oficina',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='executante_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario'),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='executante_terceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_terceirizado'),
        ),
    ]
