# Generated by Django 4.1.5 on 2024-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0006_ordem_oficina_tempo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_oficina',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
