# Generated by Django 4.1.5 on 2024-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0007_alter_servico_oficina_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico_oficina',
            name='tempo_em_servico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
