# Generated by Django 4.1.5 on 2024-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0008_servico_oficina_tempo_aguardo_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico_oficina',
            name='executante',
            field=models.CharField(choices=[('F', 'Funcionario'), ('T', 'Terceirizado')], default='Funcionario', max_length=50),
        ),
    ]
