# Generated by Django 5.0.2 on 2024-05-03 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0009_servico_oficina_executante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_servico', models.FloatField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('servico_oficina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_oficina')),
            ],
        ),
    ]
