# Generated by Django 4.1.5 on 2024-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0010_registro_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico_oficina',
            name='data_mudanca_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
