# Generated by Django 4.1.5 on 2024-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0011_servico_oficina_data_mudanca_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_oficina',
            name='data_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
