# Generated by Django 4.1.5 on 2024-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0012_ordem_oficina_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_em_servico',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
