# Generated by Django 5.0.2 on 2024-11-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        ('manutencao', '0013_alter_ordem_oficina_tempo_aguardo_peca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico_Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('insumo', models.CharField(max_length=100)),
                ('quantidade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='servico_oficina',
            name='tempo_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='status',
            field=models.CharField(choices=[('AP', 'Aguardando Peças'), ('AS', 'Aguardando Serviço'), ('ES', 'Em Serviço')], default='Em Serviço', max_length=5),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_em_servico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Ordem_Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
                ('servicos', models.ManyToManyField(blank=True, null=True, to='manutencao.servico_preventiva')),
            ],
        ),
        migrations.CreateModel(
            name='Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horimetro', models.FloatField(blank=True, null=True)),
                ('data_emissao', models.DateField()),
                ('data_insumo', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_servico', models.FloatField(default=0.0)),
                ('assinatura_responsavel', models.BooleanField(default=False)),
                ('numero', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.obras')),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.ordem_preventiva')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Tempo_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_servico', models.FloatField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('servico_oficina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_oficina')),
                ('tercerizado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_terceirizado')),
            ],
        ),
        migrations.CreateModel(
            name='Socorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_saida', models.DateTimeField()),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Servico_Socorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_servico', models.FloatField(default=0.0)),
                ('descricao', models.CharField(max_length=500)),
                ('resultado_servico', models.BooleanField(default=False)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
                ('grupo_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.grupo_servico')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.socorro')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=200)),
                ('solicitacao', models.IntegerField()),
                ('data_suprimentos', models.DateTimeField()),
                ('status', models.CharField(choices=[('BP', 'Baixa Prioridade'), ('MP', 'Média Prioridade'), ('AP', 'Alta Prioridade'), ('UR', 'Urgente')], default='Baixa Prioridade', max_length=50)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('link_solicitacao', models.CharField(blank=True, max_length=500)),
                ('observacao', models.CharField(blank=True, max_length=1000)),
                ('atendida', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
            ],
        ),
        migrations.DeleteModel(
            name='Registro_Funcionario',
        ),
    ]
