# Generated by Django 5.0.2 on 2024-08-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0013_alter_ordem_oficina_tempo_aguardo_peca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_oficina',
            name='status',
            field=models.CharField(choices=[('AP', 'Aguardando Peças'), ('AS', 'Aguardando Serviço'), ('ES', 'Em Serviço')], default='Em Serviço', max_length=5),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_em_servico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Registro_Tempo_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_servico', models.FloatField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('servico_oficina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_oficina')),
                ('tercerizado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_terceirizado')),
            ],
        ),
        migrations.DeleteModel(
            name='Registro_Funcionario',
        ),
    ]
