# Generated by Django 5.0.2 on 2024-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0013_alter_ordem_oficina_tempo_aguardo_peca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_aguardo_peca',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_aguardo_servico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico_oficina',
            name='tempo_em_servico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
