# Generated by Django 5.0.2 on 2024-11-13 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0014_servico_preventiva_servico_oficina_tempo_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_tempo_servico',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario'),
        ),
        migrations.AlterField(
            model_name='registro_tempo_servico',
            name='tercerizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.servico_terceirizado'),
        ),
    ]
