# Generated by Django 5.0.2 on 2024-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0014_alter_servico_oficina_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico_oficina',
            name='tempo_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
