# Generated by Django 5.0.2 on 2024-09-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        ('manutencao', '0015_servico_oficina_tempo_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=200)),
                ('solicitacao', models.IntegerField()),
                ('data_suprimentos', models.DateTimeField()),
                ('status', models.CharField(choices=[('BP', 'Baixa Prioridade'), ('MP', 'Média Prioridade'), ('AP', 'Alta Prioridade'), ('UR', 'Urgente')], default='Baixa Prioridade', max_length=50)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('link_solicitacao', models.CharField(blank=True, max_length=500)),
                ('observacao', models.CharField(blank=True, max_length=1000)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
            ],
        ),
    ]
