# Generated by Django 5.0.2 on 2024-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0016_solicitação'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitação',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
    ]
