# Generated by Django 5.0.2 on 2024-09-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        ('manutencao', '0017_solicitação_atendida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitação',
            new_name='Solicitacao',
        ),
    ]
