# Generated by Django 5.0.2 on 2024-09-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        ('manutencao', '0018_rename_solicitação_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_saida', models.DateTimeField()),
                ('data_chegada', models.DateField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Servico_Socorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tempo_servico', models.FloatField()),
                ('descricao', models.CharField(max_length=500)),
                ('resultado_servico', models.BooleanField(default=False)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
                ('grupo_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.grupo_servico')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario')),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.socorro')),
            ],
        ),
    ]
