# Generated by Django 5.0.2 on 2024-09-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0019_socorro_servico_socorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socorro',
            name='data_chegada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
