# Generated by Django 5.0.2 on 2024-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0020_alter_socorro_data_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_oficina',
            name='tempo_total',
            field=models.FloatField(default=0.0),
        ),
    ]
