# Generated by Django 5.0.2 on 2024-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0021_alter_ordem_oficina_tempo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico_socorro',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
