# Generated by Django 5.0.2 on 2024-09-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0022_servico_socorro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_socorro',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico_socorro',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
