# Generated by Django 5.0.2 on 2024-09-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0014_alter_servico_oficina_tempo_aguardo_peca_and_more'),
        ('manutencao', '0023_alter_servico_socorro_data_fim_and_more'),
    ]

    operations = [
    ]
