# Generated by Django 5.0.2 on 2024-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0024_merge_20240928_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_socorro',
            name='tempo_servico',
            field=models.FloatField(default=0.0),
        ),
    ]
