# Generated by Django 5.0.2 on 2024-10-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_obras_status'),
        ('manutencao', '0025_alter_servico_socorro_tempo_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico_Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('insumo', models.CharField(max_length=100)),
                ('quantidade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.equipamentos')),
                ('servicos', models.ManyToManyField(to='manutencao.servico_preventiva')),
            ],
        ),
        migrations.CreateModel(
            name='Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotimetro', models.FloatField()),
                ('data_emissao', models.DateField()),
                ('data_separados', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.obras')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.ordem_preventiva')),
            ],
        ),
    ]
