# Generated by Django 5.0.2 on 2024-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0026_servico_preventiva_ordem_preventiva_preventiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_preventiva',
            name='servicos',
            field=models.ManyToManyField(blank=True, null=True, to='manutencao.servico_preventiva'),
        ),
    ]
