# Generated by Django 5.0.2 on 2024-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0027_alter_ordem_preventiva_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='assinatura_responsável',
            field=models.BooleanField(default=False),
        ),
    ]
