# Generated by Django 5.0.2 on 2024-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0028_preventiva_assinatura_responsável'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
