# Generated by Django 5.0.2 on 2024-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0029_preventiva_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventiva',
            name='hotimetro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
