# Generated by Django 5.0.2 on 2024-10-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0030_alter_preventiva_hotimetro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventiva',
            old_name='assinatura_responsável',
            new_name='assinatura_responsavel',
        ),
        migrations.RenameField(
            model_name='preventiva',
            old_name='data_separados',
            new_name='data_insumo',
        ),
    ]
