# Generated by Django 5.0.2 on 2024-10-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0031_rename_assinatura_responsável_preventiva_assinatura_responsavel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventiva',
            old_name='hotimetro',
            new_name='horimetro',
        ),
        migrations.AddField(
            model_name='preventiva',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manutencao.funcionario'),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='tempo_servico',
            field=models.FloatField(default=0.0),
        ),
    ]
