# Generated by Django 4.1.5 on 2024-02-20 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('R', 'ROCHA'), ('T', 'TERCERIZADO')], default='ROCHA', max_length=5)),
                ('proprietario', models.CharField(max_length=50, null=True)),
                ('horímetro', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('saldo', models.FloatField(default=0)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
