# Generated by Django 4.1.5 on 2024-02-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='endereço',
            field=models.CharField(default='', max_length=100),
        ),
    ]
