# Generated by Django 4.1.5 on 2024-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_obras_endereço'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='distancia',
            field=models.IntegerField(default=0),
        ),
    ]
