# Generated by Django 5.0.2 on 2024-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_obras_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='status',
            field=models.CharField(choices=[('S', 'SALDO'), ('M', 'MEDIÇÃO')], default='SALDO', max_length=5),
        ),
    ]
