# Generated by Django 5.0.2 on 2024-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_obras_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='status',
            field=models.CharField(choices=[('S', 'SALDO'), ('M', 'MEDIÇÃO')], default='S', max_length=5),
        ),
    ]
